from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def __init__(self):
        self.evaluate = QtWidgets.QAction(MainWindow)
        self.save = QtWidgets.QAction(MainWindow)
        self.open = QtWidgets.QAction(MainWindow)
        self.create = QtWidgets.QAction(MainWindow)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menuItems = QtWidgets.QMenu(self.menubar)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.usedPoints = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.usedPointsText = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.team = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.teamText = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.availablePoints = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.availablePointsText = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.pointsLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.wicketKeeperCount = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.wicketKeeperText = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.allRounderCount = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.allRounderText = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.bowlerCount = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.bowlerText = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.batsmanCount = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.batsmanText = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.countLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.wicketKeeper = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.allRounder = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.bat = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.bowler = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.checkboxLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.selectedPlayer = QtWidgets.QListWidget(self.horizontalLayoutWidget_2)
        self.availablePlayer = QtWidgets.QListWidget(self.horizontalLayoutWidget_2)
        self.playerListLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 500)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(9, 190, 581, 261))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.playerListLayout.setContentsMargins(0, 0, 0, 0)
        self.playerListLayout.setObjectName("playerListLayout")
        self.availablePlayer.setObjectName("availablePlayer")
        self.playerListLayout.addWidget(self.availablePlayer)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.playerListLayout.addItem(spacerItem)
        self.selectedPlayer.setObjectName("selectedPlayer")
        self.playerListLayout.addWidget(self.selectedPlayer)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 100, 571, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.checkboxLayout.setContentsMargins(0, 0, 0, 0)
        self.checkboxLayout.setObjectName("checkboxLayout")
        self.bat.setObjectName("bat")
        self.bat.setEnabled(False)
        self.checkboxLayout.addWidget(self.bat)
        self.bowler.setObjectName("bowler")
        self.bowler.setEnabled(False)
        self.checkboxLayout.addWidget(self.bowler)
        self.allRounder.setObjectName("allRounder")
        self.allRounder.setEnabled(False)
        self.checkboxLayout.addWidget(self.allRounder)
        self.wicketKeeper.setObjectName("wicketKeeper")
        self.wicketKeeper.setEnabled(False)
        self.checkboxLayout.addWidget(self.wicketKeeper)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(10, 30, 584, 51))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.countLayout.setContentsMargins(0, 0, 0, 0)
        self.countLayout.setObjectName("countLayout")
        self.batsmanText.setObjectName("batsmanText")
        self.countLayout.addWidget(self.batsmanText)
        self.batsmanCount.setObjectName("batsmanCount")
        self.countLayout.addWidget(self.batsmanCount)
        self.bowlerText.setObjectName("bowlerText")
        self.countLayout.addWidget(self.bowlerText)
        self.bowlerCount.setObjectName("bowlerCount")
        self.countLayout.addWidget(self.bowlerCount)
        self.allRounderText.setObjectName("allRounderText")
        self.countLayout.addWidget(self.allRounderText)
        self.allRounderCount.setObjectName("allRounderCount")
        self.countLayout.addWidget(self.allRounderCount)
        self.wicketKeeperText.setObjectName("wicketKeeperText")
        self.countLayout.addWidget(self.wicketKeeperText)
        self.wicketKeeperCount.setObjectName("wicketKeeperCount")
        self.countLayout.addWidget(self.wicketKeeperCount)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(10, 150, 571, 31))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.pointsLayout.setContentsMargins(0, 0, 0, 0)
        self.pointsLayout.setObjectName("pointsLayout")
        self.availablePointsText.setObjectName("availablePointsText")
        self.pointsLayout.addWidget(self.availablePointsText)
        self.availablePoints.setObjectName("availablePoints")
        self.pointsLayout.addWidget(self.availablePoints)
        self.teamText.setObjectName("teamText")
        self.pointsLayout.addWidget(self.teamText)
        self.team.setObjectName("team")
        self.pointsLayout.addWidget(self.team)
        self.usedPointsText.setObjectName("usedPointsText")
        self.pointsLayout.addWidget(self.usedPointsText)
        self.usedPoints.setObjectName("usedPoints")
        self.pointsLayout.addWidget(self.usedPoints)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 600, 25))
        self.menubar.setObjectName("menubar")
        self.menubar.setNativeMenuBar(False)
        self.menuItems.setObjectName("menuItems")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.create.setObjectName("create")
        self.open.setObjectName("open")
        self.save.setObjectName("save")
        self.evaluate.setObjectName("evaluate")
        self.menuItems.addAction(self.create)
        self.menuItems.addAction(self.open)
        self.menuItems.addAction(self.save)
        self.menuItems.addAction(self.evaluate)
        self.menubar.addAction(self.menuItems.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.bat.setText(_translate("MainWindow", "Bat"))
        self.bowler.setText(_translate("MainWindow", "Bowl"))
        self.allRounder.setText(_translate("MainWindow", "All"))
        self.wicketKeeper.setText(_translate("MainWindow", "WK"))
        self.batsmanText.setText(_translate("MainWindow", "Batsmen (BAT)"))
        self.batsmanCount.setText(_translate("MainWindow", "##"))
        self.bowlerText.setText(_translate("MainWindow", "Bowlers (BOWL)"))
        self.bowlerCount.setText(_translate("MainWindow", "##"))
        self.allRounderText.setText(_translate("MainWindow", "Allrounders (AR)"))
        self.allRounderCount.setText(_translate("MainWindow", "##"))
        self.wicketKeeperText.setText(_translate("MainWindow", "Wicket-keeper (WK)"))
        self.wicketKeeperCount.setText(_translate("MainWindow", "##"))
        self.availablePointsText.setText(_translate("MainWindow", "Point Available"))
        self.availablePoints.setText(_translate("MainWindow", "##"))
        self.teamText.setText(_translate("MainWindow", "Team Name - "))
        self.team.setText(_translate("MainWindow", "##"))
        self.usedPointsText.setText(_translate("MainWindow", "Point Used "))
        self.usedPoints.setText(_translate("MainWindow", "##"))
        self.menuItems.setTitle(_translate("MainWindow", "Manage Teams"))
        self.create.setText(_translate("MainWindow", "CREATE Teams"))
        self.open.setText(_translate("MainWindow", "OPEN Teams"))
        self.save.setText(_translate("MainWindow", "SAVE Teams"))
        self.evaluate.setText(_translate("MainWindow", "EVALUATE Teams"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
