# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 500)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(9, 190, 581, 261))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.list1 = QtWidgets.QListWidget(self.horizontalLayoutWidget_2)
        self.list1.setObjectName("list1")
        self.horizontalLayout_2.addWidget(self.list1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.list2 = QtWidgets.QListWidget(self.horizontalLayoutWidget_2)
        self.list2.setObjectName("list2")
        self.horizontalLayout_2.addWidget(self.list2)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 100, 571, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Bat = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.Bat.setObjectName("Bat")
        self.horizontalLayout.addWidget(self.Bat)
        self.Bowl = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.Bowl.setObjectName("Bowl")
        self.horizontalLayout.addWidget(self.Bowl)
        self.All = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.All.setObjectName("All")
        self.horizontalLayout.addWidget(self.All)
        self.WK = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.WK.setObjectName("WK")
        self.horizontalLayout.addWidget(self.WK)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(10, 30, 571, 51))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.Batsman_1 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.Batsman_1.setObjectName("Batsman_1")
        self.horizontalLayout_3.addWidget(self.Batsman_1)
        self.Batsman_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.Batsman_2.setObjectName("Batsman_2")
        self.horizontalLayout_3.addWidget(self.Batsman_2)
        self.Bowlers_1 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.Bowlers_1.setObjectName("Bowlers_1")
        self.horizontalLayout_3.addWidget(self.Bowlers_1)
        self.Bowlers_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.Bowlers_2.setObjectName("Bowlers_2")
        self.horizontalLayout_3.addWidget(self.Bowlers_2)
        self.Allrounders_1 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.Allrounders_1.setObjectName("Allrounders_1")
        self.horizontalLayout_3.addWidget(self.Allrounders_1)
        self.Allrounders_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.Allrounders_2.setObjectName("Allrounders_2")
        self.horizontalLayout_3.addWidget(self.Allrounders_2)
        self.Wicketkeeper_1 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.Wicketkeeper_1.setObjectName("Wicketkeeper_1")
        self.horizontalLayout_3.addWidget(self.Wicketkeeper_1)
        self.Wicketkeeper_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.Wicketkeeper_2.setObjectName("Wicketkeeper_2")
        self.horizontalLayout_3.addWidget(self.Wicketkeeper_2)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(10, 150, 571, 31))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pointAvailableText = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.pointAvailableText.setObjectName("pointAvailableText")
        self.horizontalLayout_4.addWidget(self.pointAvailableText)
        self.pointAvailableBox = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.pointAvailableBox.setObjectName("pointAvailableBox")
        self.horizontalLayout_4.addWidget(self.pointAvailableBox)
        self.teamNameText = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.teamNameText.setObjectName("teamNameText")
        self.horizontalLayout_4.addWidget(self.teamNameText)
        self.teamNameBox = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.teamNameBox.setObjectName("teamNameBox")
        self.horizontalLayout_4.addWidget(self.teamNameBox)
        self.pointUsedText = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.pointUsedText.setObjectName("pointUsedText")
        self.horizontalLayout_4.addWidget(self.pointUsedText)
        self.pointUsedBox = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.pointUsedBox.setObjectName("pointUsedBox")
        self.horizontalLayout_4.addWidget(self.pointUsedBox)
        self.horizontalLayoutWidget_2.raise_()
        self.horizontalLayoutWidget.raise_()
        self.horizontalLayoutWidget_3.raise_()
        self.Allrounders_1.raise_()
        self.horizontalLayoutWidget_4.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 600, 21))
        self.menubar.setObjectName("menubar")
        self.menuManage_Teams = QtWidgets.QMenu(self.menubar)
        self.menuManage_Teams.setObjectName("menuManage_Teams")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.CREATE = QtWidgets.QAction(MainWindow)
        self.CREATE.setObjectName("CREATE")
        self.OPEN = QtWidgets.QAction(MainWindow)
        self.OPEN.setObjectName("OPEN")
        self.SAVE = QtWidgets.QAction(MainWindow)
        self.SAVE.setObjectName("SAVE")
        self.EVALUATE = QtWidgets.QAction(MainWindow)
        self.EVALUATE.setObjectName("EVALUATE")
        self.menuManage_Teams.addAction(self.CREATE)
        self.menuManage_Teams.addAction(self.OPEN)
        self.menuManage_Teams.addAction(self.SAVE)
        self.menuManage_Teams.addAction(self.EVALUATE)
        self.menubar.addAction(self.menuManage_Teams.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Bat.setText(_translate("MainWindow", "Bat"))
        self.Bowl.setText(_translate("MainWindow", "Bowl"))
        self.All.setText(_translate("MainWindow", "All"))
        self.WK.setText(_translate("MainWindow", "WK"))
        self.Batsman_1.setText(_translate("MainWindow", "Batsmen (BAT)"))
        self.Batsman_2.setText(_translate("MainWindow", "##"))
        self.Bowlers_1.setText(_translate("MainWindow", "Bowlers (BOWL)"))
        self.Bowlers_2.setText(_translate("MainWindow", "##"))
        self.Allrounders_1.setText(_translate("MainWindow", "Allrounders (AR)"))
        self.Allrounders_2.setText(_translate("MainWindow", "##"))
        self.Wicketkeeper_1.setText(_translate("MainWindow", "Wicket-keeper (WK)"))
        self.Wicketkeeper_2.setText(_translate("MainWindow", "##"))
        self.pointAvailableText.setText(_translate("MainWindow", "Point Available"))
        self.pointAvailableBox.setText(_translate("MainWindow", "##"))
        self.teamNameText.setText(_translate("MainWindow", "Team Name - "))
        self.teamNameBox.setText(_translate("MainWindow", "##"))
        self.pointUsedText.setText(_translate("MainWindow", "Point Used "))
        self.pointUsedBox.setText(_translate("MainWindow", "##"))
        self.menuManage_Teams.setTitle(_translate("MainWindow", "Manage Teams"))
        self.CREATE.setText(_translate("MainWindow", "CREATE Teams"))
        self.OPEN.setText(_translate("MainWindow", "OPEN Teams"))
        self.SAVE.setText(_translate("MainWindow", "SAVE Teams"))
        self.EVALUATE.setText(_translate("MainWindow", "EVALUATE Teams"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

